Dao
elizaochoa86/pets-api pull request #3
Opened 2020-06-18 00:15 UTC by elizaochoa86

Complete DAO Test.

2020-06-18 04:28 UTC, reyniergt requested changes

2020-06-18 04:28 UTC, reyniergt commented on src/main/java/com/javaprojects/petsapi/controllers/PetController.java
> +        pet.setId(id);
what happen if the id doesnt exists?

2020-06-18 04:28 UTC, reyniergt commented on src/main/java/com/javaprojects/petsapi/controllers/PetController.java
> +        service.delete(id);
what happen if the id doesnt exists?

2020-06-18 04:28 UTC, reyniergt commented on src/main/java/com/javaprojects/petsapi/services/PetServiceImpl.java
> +        petDAO.delete(id);
what happen if the id doesnt exists?

2020-06-18 04:28 UTC, reyniergt commented on src/main/java/com/javaprojects/petsapi/services/PetServiceImpl.java
> +        for (Pet pet:
It could be more elegant to use java 8 streams

2020-06-18 04:28 UTC, reyniergt commented on src/main/java/com/javaprojects/petsapi/services/RaceServiceImpl.java
> +        for (Race race:
It could be more elegant to use java 8 streams

2020-06-18 04:28 UTC, reyniergt commented on src/main/java/com/javaprojects/petsapi/services/RaceServiceImpl.java
> +        raceDAO.delete(id);
what happen if the id doesnt exists?

2020-06-18 04:28 UTC, reyniergt commented on src/main/java/com/javaprojects/petsapi/services/SpeciesServiceImpl.java
> +    private List<SpeciesDTO> convertToListSpeciesDTO(List<Species> species){
It would be more elegant to use java 8 lambdas

2020-06-22 02:54 UTC, elizaochoa86 commented on src/main/java/com/javaprojects/petsapi/controllers/PetController.java
> +        pet.setId(id);
solved

2020-06-22 23:45 UTC, reyniergt approved these changes

2020-06-22 23:49 UTC, merged